version: '3.5'

services:
  analyticservice.api:
    image: ${DOCKER_REGISTRY-}analyticserviceapi
    build:
      context: .
      dockerfile: AnalyticService.API/Dockerfile
    container_name: "analytic-service"
    networks:
      - cards-network
    ports:
        - "5003:8080"
        - "5004:8081"

networks:
  cards-network:
    external: true