version: '3.9'

services:
  statisticservice.api:
    environment:
      CONNECTION_STRING: "Host=172.17.0.1;Port=5432;User Id=postgres;Password=admin;Database=cards_statistic_tb;"
    container_name: statistic-service
    build:
      context: .
      dockerfile: StatisticService.API/Dockerfile
    networks:
        - cards-network
    ports:
        - "5003:8080"
        - "5004:8081"
networks:
  cards-network:
    external: true