version: '3.5'

services:
  statisticservice.api:
    environment:
      CONNECTION_STRING: ${CONNECTION_STRING}
    container_name: statistic-service
    image: ${DOCKER_REGISTRY-}statisticserviceapi
    build:
      context: .
      dockerfile: StatisticService.API/Dockerfile
    networks:
        - cards-network
    # В целом даже порты прокидывать не надо. Так как все через бридж будет работать. 
    ports:
        - "5003:8080"
        - "5004:8081"
networks:
  cards-network:
    external: true