name: statistic-service
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Добавление SSH key
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
            mkdir -p /home/runner/.ssh
            ssh-keyscan ${{ secrets.SSH_HOST }} >> /home/runner/.ssh/known_hosts
            echo "${{ secrets.SSH_KEY }}" > /home/runner/.ssh/github_actions
            chmod 600 /home/runner/.ssh/github_actions
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null
            ssh-add /home/runner/.ssh/github_actions

      - name: Клонирование или обновление репозитория
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Проверяем, существует ли директория
            if [ -d "/var/www/analyticService" ]; then
              echo "Директория существует, очищаем её..."
              sudo rm -rf /var/www/analyticService/*
              sudo rm -rf /var/www/analyticService/.*
            else
              echo "Директория не существует, создаём её..."
              sudo mkdir -p /var/www/analyticService
              sudo chown -R ${{ secrets.SSH_USERNAME }}:${{ secrets.SSH_USERNAME }} /var/www/analyticService
            fi
      
            cd /var/www/analyticService
            git clone https://github.com/HinodeMyojo/AnalyticService.git . || {
              echo "Ошибка при клонировании репозитория"
              exit 1
            }
      
            echo "Репо успешно клонирован или обновлён."
            
      - name: Деплой сервера
        uses: appleboy/ssh-action@v0.1.6
        env:
          CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/analyticService/
            echo "Стартуем деплой"
            docker-compose -f docker-compose-prod.yml up -d --build
            echo "Деплой завершился."

      - name: Проверка состояния контейнеров
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker ps --format "table {{.Names}}\t{{.Status}}"

